### ISSUE TITLE
MvxForm issue on Android when click Back button

### ISSUE THREAD

**Issue by flashvnn** [MobiliTips/MvxPlugins#6]
I got issue when using MvxForm for Android app, when click back button it close app, but when i open app again, then click back button it don't close app correctly.
Please check video issue here: https://youtu.be/N8PvlO54dK0

**Comment by MobiliTips** [comment]
Sorry for delay, holidays...
Well as MvvmCross 4 will officially support Xamarin Forms (see on MvvmCross's Github) I wonder if it's still a need I work on this side project.
I think you should now use the official implementation available with MvvmCross 4 or maybe fork my project to correct it.
I think I will no longer work on it.
